[[headers]]
  for = "/*.scss"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "stylesheet"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "font/woff"    

    [[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "font/woff2"


    /fonts/terminal/*.woff
  Access-Control-Allow-Origin: *
  Content-Type: application/font-woff

/fonts/terminal/*.woff2
  Access-Control-Allow-Origin: *
  Content-Type: application/font-woff2   