[[headers]]
  for = "/*.scss"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "stylesheet"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"    